name: Build and deploy WAR app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permissions for Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test  # Assumes tests are handled separately or not needed for build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: build/libs/*.war

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: my-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myazurewebapp'  # Replace with your actual Azure Web App name
          slot-name: 'production'    # Optional: specify if using deployment slots
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.war'
